default: &default
  adapter: mysql2
  pool: 10
  timeout: 5000
  username: root
  password: mypassword
  host: 127.0.0.1
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: tiktaktoe_dev

test:
  <<: *default
  database: tiktaktoe_test

production:
  <<: *default
  database: tiktaktoe_prod

jenkins:
  <<: *default
  database: jenkins_eds_mms
