default: &default
  adapter: mysql2
  pool: 10
  timeout: 5000
  username: patilcm
  password: Mypassword@1234
  host: patilcm.mysql.pythonanywhere-services.com
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: tiktaktoe_dev

test:
  <<: *default
  database: tiktaktoe_test

production:
  <<: *default
  database: tiktaktoe_prod

jenkins:
  <<: *default
  database: jenkins_eds_mms
